protein_file: data/7zzs_clean.pdb
metal_file: data/zn.pdb

protein_ff: amber/ff14SB.xml
solvent_ff: amber/tip3pfb_standard.xml

ph: 7.0

padding: 1.0e-9
ionicStrength: 0.15

nonbondedCutoff: 1.0e-9
ewaldErrorTolerance: 5.0e-4
rigidWater: true
constraintTolerance: 1.0e-6
temperature: 300
friction: 1.0
pressure: 1.0
barostatInterval: 25

dt: 2.0e-15
equilibrationSteps: 50000
steps: 50000000
reporterStep: 10000
checkpointStep: 10000
cuda: true