# general
experiment_dir: 

# preprocess
protein_path:
ligand_dir_path:
ph: 7.0
metal: ZN
# relative path from openmm/app/data
protein_ff: amber14/protein.ff14SB.xml
solvent_ff: amber14/tip3pfb.xml

# simulation
nonbondedCutoff: 1.0
ewaldErrorTolerance: 5.0e-4
rigidWater: True
constraintTolerance: 1.0e-6
temperature: 300
friction: 1.0
pressure: 1.0
barostatInterval: 25
# femto second
dt: 2.0
equilibrationSteps: 50000
# 50000000steps(dt=2.0fs) -> 100ns
steps: 50000000
reporterStep: 10000
checkpointStep: 10000
platform: CUDA
platformProperties: single